services:
  webapp:
    build:
      context: ./node-webapp
    ports:
      - "3000:3000"
    volumes:
      - ./node-webapp:/app
      - /app/node_modules
    environment:
      - PORT=3000
    restart: unless-stopped
